[features]
seeds = false
skip-lint = false
[programs.localnet]
vault_program = "CUgwUMb216dRv3oMD19kZ4f8tPFC6ubmexnHtmXScj2e"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/ak/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
